version: '3.5'

services: 
  backend: 
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    env_file: 
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules  # <-- Prevents overwriting node_modules
    depends_on:
      - db
  client: 
    build: 
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules  # <-- Prevents overwriting node_modules

    depends_on:
      - backend
    env_file: 
      - ./client/.env
  db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db

