FROM node:18-alpine

WORKDIR /app    

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

# RUN yarn global add @nestjs/cli
RUN yarn global add @nestjs/cli@10.2.0

# RUN yarn build

EXPOSE 3001

CMD ["yarn", "start:dev"]